/*$file${qm_src::serdisperr.h} #############################################*/
/*
* Model: balkonowy_rx_ult_.qm
* File:  ${qm_src::serdisperr.h}
*
* This code has been generated by QM 4.3.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${qm_src::serdisperr.h} ##########################################*/
#ifndef serdisperr_h
#define serdisperr_h

/* symbols definitions */

/* active objects' "constructors" */

/*$declare${AOs::SerDispErr_ctor} ##########################################*/
/*${AOs::SerDispErr_ctor} ..................................................*/
QHsm * SerDispErr_ctor(QTimeEvt * const blinkEvt);
/*$enddecl${AOs::SerDispErr_ctor} ##########################################*/

/* instantiation of the orthogonal components */


/* opaque pointer to AOs */


#endif /* serdisperr_h */