/*$file${qm_src::timer.h} ##################################################*/
/*
* Model: balkonowy_rx_ult_.qm
* File:  ${qm_src::timer.h}
*
* This code has been generated by QM 4.3.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${qm_src::timer.h} ###############################################*/
#ifndef timer_h
#define timer_h

/* symbols definitions */


/* active objects' "constructors" */


/* instantiation of the orthogonal components */


/* opaque pointer to AOs */

/*$declare${AOs::the_Ticker0} ##############################################*/
extern QActive * const the_Ticker0;
/*$enddecl${AOs::the_Ticker0} ##############################################*/

#endif /* timer_h */